name: Case Converter CI
on: [push]
jobs:
    unit-tests:
        runs-on: ubuntu-latest
        steps:
            - name: Check out code
              uses: actions/checkout@v4
            - name: Setup node
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
            - name: Install packages
              working-directory: next-app
              run: npm ci
            - name: Run unit tests
              working-directory: next-app
              run: npm test
